### ISSUE TITLE
Can't open qjoypad

### ISSUE THREAD

**Issue by aciddburnz** [MrJackSpade/RG35XXP-XFCE#1]
Qjoypad won't open since there is another instance open, ive tried everything to find out how to quit the other instance but have failed.

**Comment by MrJackSpade** [comment]
`pkill -f qjoypad` will kill the running instance but you'll lose the ability to interact with the device in the meantime, so you'll need an external mouse connected, or to be logged in through VNC

I would like to modify whatever launch parameter is causing it to start as a hidden process but I haven't gotten around to that part yet.

**Comment by MrJackSpade** [comment]
The scripts have been updated and this is no longer applicable
