### ISSUE TITLE
Will there be any updates?

### ISSUE THREAD

**Issue by 14cola** [MrJackSpade/RG35XXP-XFCE#12]
I hope moolight can be added to the system

**Comment by MrJackSpade** [comment]
Yeah, I just realized that Michael MJD did a video on this and probably brought a lot of views. 

I'll try and create an updated image over the next week or two and push it up.

I'm going to have to get back into how this whole thing works though, it's been a while and I've forgotten a lot

**Comment by MrJackSpade** [comment]
The scripts have been updated and this is no longer applicable
