### ISSUE TITLE
Wireless Internet Interfaces not showing.

### ISSUE THREAD

**Issue by Victorinox13** [MrJackSpade/RG35XXP-XFCE#18]
Is there a way to show the wifi interfaces on the emulator using xcfe. Right now using iwconfig it lists a bunch of interface but all empty... I would like to do wifi penetration testing, I also have a wifi adapter I can plugin.

**Comment by kasra9400** [comment]
i installed network manager and it works on xfce. it could help
using this commanad 
```
sudo apt install network-manager
sudo apt install network-manager-gnome
sudo systemctl enable NetworkManager.service
```

**Comment by MrJackSpade** [comment]
Was the gnome network manager actually required specifically? 

I'm concerned about installing it by default due to the limited space

@kasra9400

**Comment by kasra9400** [comment]
> Was the gnome network manager actually required specifically?

i just installed that for wifi interface and search networks or switch between them without going to default anbernic menu 
oh by the way when you open the interface it shows double networks per each .
