### ISSUE TITLE
Am I doing something wrong with cbepx-me (modded v 2.9 1.1.6 rg35xxH)

### ISSUE THREAD

**Issue by xosona** [MrJackSpade/RG35XXP-XFCE#19]
When I boot the stock image 2024-09-10 UPDATE on my RG35XXSP, it displays the Anbernic logo. I've waited over 20 mins and nothing happens. 

I tried formatting to FAT32 and exFAT with Rufus before flashing the image.

**Comment by kasra9400** [comment]
> When I boot the stock image 2024-09-10 UPDATE on my RG35XXSP, it displays the Anbernic logo. I've waited over 20 mins and nothing happens.
> 
> I tried formatting to FAT32 and exFAT with Rufus before flashing the image.

im not sure where the problem coming from, but i installed xfce on modded stock os from cbepx-me (modded v 2.9 1.1.6 rg35xxH) without problem
also check you have good quality of sdcard and format sdcard with sdcard formatter app and then reflash the os

**Comment by MrJackSpade** [comment]
Unfortunately I can't help with this, as a modded image is no longer "stock".

The modded images often resize and edit partition layouts, frequently removing the space required for the installer to work.

I will leave this open in case anyone else wants to look into it though

**Comment by xosona** [comment]
No luck with the image. I tried a few different SD Cards (SanDisk and Samsung) that have worked for other handhelds I use. Formatted in Rufus and tried flashing in Rufus and Balena, but no luck with the image. It always hangs on the Anbernic logo. 

I had success with the original directions, though. Thanks for working on this! It is neato.
