### ISSUE TITLE
User Account instead of Admin Possible?

### ISSUE THREAD

**Issue by JazzJohannes** [MrJackSpade/RG35XXP-XFCE#23]
I am trying to install Portmaster on this distro, according to Portmaster it's possible in XFCE with this kernel (it being v2.4 and compatible): https://docs.safing.io/portmaster/install/linux

However I would need to create a User Account, is there any way to get the account manager installed in this distro, as the command line method is very bug-prone and complicated...?

**Comment by MrJackSpade** [comment]
Does the software not allow you to install it as root?

It might be possible to add a secondary user account as part of the setup specifically for instances like this, but I'm not sure if it would actually function or not.

**Comment by JazzJohannes** [comment]
Yeah the feedback it gave me specifically from the command line was that it needs to be installed on a user account not root.

**Comment by MrJackSpade** [comment]
Ive created a second user account just named "user" with a password of "user", however I do not know if it will resolve your problem.
