### ISSUE TITLE
Version for rg40xxh

### ISSUE THREAD

**Issue by rafikov** [MrJackSpade/RG35XXP-XFCE#24]
I wonder how much effort it would take to add a version for rg40xxh?

They are very similar by specs but when I'm running this firmware on my rg40xxh, there are vertical lines of different color on the screen and they seem to react to when I press the d-pad, but otherwise it just doesn't work.

**Comment by MrJackSpade** [comment]
I would need a rg40xxh to test on. If someone wants to buy me one then I'll attempt to make it work and consider it payment for the effort, however I (unfortunately) don't have the time/money to invest in updating this for additional devices.
