### ISSUE TITLE
NDS emulation is broken after install

### ISSUE THREAD

**Issue by ravensdan** [MrJackSpade/RG35XXP-XFCE#25]
as the titile say nds emulation is not working at least on my rg 35xxh on 1.1.7 mod stock

**Comment by MrJackSpade** [comment]
If this is an issue on 1.1.7 stock then I'll resolve it, however I don't have the time to dedicate to resolving issues on non-standard firmware, regardless of how popular they are.

**Comment by techcat-dev** [comment]
This also happened to me on the stock Anbernic firmware on my rg35xxsp, and the modded firmware too. 
I'd enjoy it if you supported the modded firmware too, since it fixes some of the major issues present in the stock firmware.

**Comment by MrJackSpade** [comment]
Does it fail when you load the content *from within* retroarch, or does it only fail when you select the game through "RA Game"?

You can open retroarch directly by going into the settings and selecting `Retroarch Settings > Launch Retroarch`

**Comment by MrJackSpade** [comment]
Figured out what it is. Turns out the broken audio device reported in another bug, was preventing Drastic (the default emulator) from opening, while Retroarch was swallowing the error.
