### ISSUE TITLE
How to change language to English in XFCE?

### ISSUE THREAD

**Issue by johnsledget** [MrJackSpade/RG35XXP-XFCE#26]
After I run install_xfce.sh and run xfce in app. I notice Japanese fonts in desktop and its text. How can we change this to English?

**Comment by MrJackSpade** [comment]
See steps 4 and 5 under [Installation](https://github.com/MrJackSpade/RG35XXP-XFCE?tab=readme-ov-file#installation)

**Comment by johnsledget** [comment]
My bad I didn't noticed it. Thanks!
