### ISSUE TITLE
Sound Audio Mixer stop working when log out. Require a reboot to fix the issue

### ISSUE THREAD

**Issue by LuckyTechnology** [MrJackSpade/RG35XXP-XFCE#29]
Sound default to internal. Only works for system music, Browser audio stop working.
Unable to switch to output to HDMI

Temporary Fix Solution:
Require a reboot to fix the issue.

**Comment by MrJackSpade** [comment]
https://github.com/MrJackSpade/RG35XXP-XFCE/commit/a6912a889a90dc8683c701066bd3c7e45c41aae7

This appears to correct the issue. Hopefully it doesn't cause new ones.

**Comment by LuckyTechnology** [comment]
I see that the Release is not updated.
Do you need to update the Release/ARM-64

**Comment by MrJackSpade** [comment]
Yes, you are absolutely right. Thank you.

I've pushed up to the release directory. 

Its going to take me a minute to get used to the new project structure.

**Comment by LuckyTechnology** [comment]
Sorry to disturb again, :(
Unfortunately I notice that the device auto set to sound output that is not the System Device Sound.
For the Build-in Audio Stereo, I see 2 options the top and bottom. 
It auto set to the Bottom Build-in Audio Stereo which work for Mini HDMI output

When the reboot it default to the bottom and the internal system device unable to output sound for the music and browser. 

I do see the option to disable the sound for the outputs. 
Thank you

**Comment by MrJackSpade** [comment]
> Unfortunately I notice that the device auto set to sound output that is not the System Device Sound.

I have honestly been trying to find a way to fix this for months now and haven't been able to.

The line within the `xinitrc` file

> pactl set-default-sink alsa_output.platform-soc_03000000_ahub1_mach.stereo-fallback

Is supposed to fix it when XFCE is booted, but it doesn't. When you run it on the command line within XFCE, or over SSH when XFCE is running, it works fine. I just haven't been able to find the "correct" place within the boot process to execute this in a way that actually solves the problem.
