### ISSUE TITLE
RunMe.desktop still require ?

### ISSUE THREAD

**Issue by LuckyTechnology** [MrJackSpade/RG35XXP-XFCE#31]
Is the RunMe.desktop still necessary ?
"\home\root\Desktop\RunMe.desktop"
It appear that the sound and language has already been configured.
Uncertain if the time UTC correct.

**Comment by MrJackSpade** [comment]
Removed

https://github.com/MrJackSpade/RG35XXP-XFCE/commit/6dd0bd03e76ccdb781f104f063996b58002dd2f4
