### ISSUE TITLE
Mouse scroll using the system device joycons peripherals

### ISSUE THREAD

**Issue by LuckyTechnology** [MrJackSpade/RG35XXP-XFCE#33]
Do you know how to set a way to mouse scroll using the system device joycons peripherals. 

I'm not sure how to configure a mouse scroll on Qjoypad. Instead of using a USB mouse. 
It would be useful for the the file setting, file explorer scrolls etc.
Thank you

**Comment by LuckyTechnology** [comment]
Not certain if this is possible. :(

**Comment by MrJackSpade** [comment]
The default configuration has (had?) mouse scroll assigned to the shoulder buttons. I don't know if its L1/R1 or L2/R2

I'm looking at the file now though and I don't see an entry for it... Its definitely possible though, now I have to recheck to see if its actually working or if something borked the config

**Comment by LuckyTechnology** [comment]
I test on RG35XX H model

I have to manually set it to work. It doesn’t auto work for someone new.

For example, after complete installation using the release. Then Click XFCE

It will require mouse and keyboard 
The joycons axis are not configured correctly lol

Thank you

**Comment by MrJackSpade** [comment]
> It doesn’t auto work for someone new.

It does for me, which is why I want to figure out whats going on with yours and how I can prevent it.

Every time I do a release, I completely wipe my SD card and set up the entire system from scratch, which is also why I don't support CFW, because the "Set everything up from scratch" step takes like 30+ minutes every time. 

Did you download the release using GIT, or did you download it as a Zip?

**Comment by LuckyTechnology** [comment]
Same. I wipe clean and start from scratch. 
I notice this when I first found out this project last week. 

I use the zip. 

I test it for over a week lol I had to manually set up using keyboard and mouse then save a copy.

Then I just import it into the Qjoypad

System Version
Using the latest version 1.1.8

**Comment by MrJackSpade** [comment]
What do you have for your QJoyPad configuration? The one you posted in the other thread appears to be the same as mine, is that it?

**Comment by LuckyTechnology** [comment]
This works for me. Unfortunately your default script only have 2 axis 
Note

Filename: Default.lyt
I set Select button to Mouse Left Click also
I set Start button to Mouse Right Click also

Joystick 1 {
Axis 1: gradient, maxSpeed 2, mouse+h
Axis 2: gradient, maxSpeed 2, mouse+v
Axis 3: gradient, maxSpeed 2, mouse+h
Axis 4: gradient, maxSpeed 2, mouse+v
Axis 5: gradient, maxSpeed 2, mouse+h
Axis 6: gradient, maxSpeed 2, mouse+v
Button 5: mouse 1
Button 6: mouse 3
Button 7: mouse 1
Button 8: mouse 3
}

**Comment by LuckyTechnology** [comment]
In comparison, this is your current default. 
I see that you set up mouse 5 and 4
I have not test that out the configuration on an extended or gaming mouse

Not sure of which system model. 
Release/ARM-64/payload/.qjoypad3/Default.lyt
