### ISSUE TITLE
Install Arm64 apps using terminal

### ISSUE THREAD

**Issue by LuckyTechnology** [MrJackSpade/RG35XXP-XFCE#36]
I try to install an arm app using terminal but it’s giving an error. Do you know if any apps will install and work? 

App: 
https://www.plex.tv/media-server-downloads/?cat=computer&plat=linux#plex-media-server

https://downloads.plex.tv/plex-media-server-new/1.41.2.9200-c6bbc1b53/debian/plexmediaserver_1.41.2.9200-c6bbc1b53_arm64.deb

**Comment by MrJackSpade** [comment]
Are you sure you want to install the *server* specifically, and not the client?

I would be surprised if the server was able to function well enough to be usable, considering its not going to have access to the GPU.

**Comment by LuckyTechnology** [comment]
Yeah. On the same network it does not require transcoding. Direct play uses the original quality resolution. No transcoding = no gpu rendering. 

Do you know how to get arm64 apps to install. I try installing any apps but couldn’t get it to work.

**Comment by LuckyTechnology** [comment]
It appear that it install but the app doesn’t show up on start.

sudo systemctl start (enter app name)

sudo systemctl start plexmediaserver

I got it to work. Wow it run amazingly with direct play. 
4K HDR works on client devices

![IMG_7338](https://github.com/user-attachments/assets/fe60e047-ef81-4ff0-ac92-9d204092de38)
![IMG_7339](https://github.com/user-attachments/assets/88ab4851-663e-4698-adcf-0ac024269239)
